openapi: 3.0.3
info:
  title: Enhanced OCR API with Gemini Integration
  description: Enhanced image processing endpoint for Vietnamese bill OCR using Google Gemini
  version: 2.0.0

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /api/ocr:
    post:
      summary: Process bill images through Gemini OCR
      description: |
        Upload one or more bill images for OCR processing through Google Gemini.
        Images are processed sequentially and return structured bill data.
      operationId: processOcrImages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Image files to process (max 10 files, 20MB each)
                  maxItems: 10
                options:
                  $ref: '#/components/schemas/ProcessingOptions'
            encoding:
              images:
                contentType: image/jpeg, image/png
      responses:
        '200':
          description: Successfully processed images
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OCRResponse'
        '400':
          description: Invalid request (bad image format, size exceeded, etc.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Missing or invalid Gemini API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Gemini API unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableError'

components:
  schemas:
    ProcessingOptions:
      type: object
      properties:
        timeout_seconds:
          type: integer
          minimum: 10
          maximum: 120
          default: 45
          description: Processing timeout per image
        language_hint:
          type: string
          default: "vi"
          description: Language hint for OCR (Vietnamese)
        confidence_threshold:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          default: 0.5
          description: Minimum confidence for field extraction

    OCRResponse:
      type: object
      required:
        - results
        - processing_summary
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/BillExtractionResult'
          description: Extraction results for each processed image
        processing_summary:
          $ref: '#/components/schemas/ProcessingSummary'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ProcessingError'
          description: Non-fatal errors encountered during processing

    BillExtractionResult:
      type: object
      required:
        - image_index
        - extracted_data
        - confidence_scores
        - processing_time_ms
      properties:
        image_index:
          type: integer
          description: Index of the image in the original request (0-based)
        extracted_data:
          $ref: '#/components/schemas/BillData'
        confidence_scores:
          $ref: '#/components/schemas/ConfidenceScores'
        processing_time_ms:
          type: integer
          description: Processing time for this image in milliseconds

    BillData:
      type: object
      description: Structured bill data matching database schema
      properties:
        form_no:
          type: string
          nullable: true
          description: Form number (e.g., "Mẫu 01-GTKT")
        invoice_no:
          type: string
          nullable: true
          description: Invoice number
        tax_code:
          type: string
          nullable: true
          description: Company tax identification code
        company_name:
          type: string
          nullable: true
          description: Issuing company name
        company_address:
          type: string
          nullable: true
          description: Company address
        buyer_name:
          type: string
          nullable: true
          description: Customer/buyer name
        buyer_address:
          type: string
          nullable: true
          description: Customer address
        issue_date:
          type: string
          format: date
          nullable: true
          description: Invoice issue date (YYYY-MM-DD)
        total_amount:
          type: string
          pattern: '^-?\d+(\.\d{1,2})?$'
          nullable: true
          description: Total amount as decimal string
        tax_amount:
          type: string
          pattern: '^-?\d+(\.\d{1,2})?$'
          nullable: true
          description: Tax amount as decimal string
        tax_rate:
          type: string
          pattern: '^-?\d+(\.\d{1,2})?$'
          nullable: true
          description: Tax rate percentage as decimal string
        payment_method:
          type: string
          nullable: true
          description: Payment method description
        notes:
          type: string
          nullable: true
          description: Additional notes or description

    ConfidenceScores:
      type: object
      required:
        - overall
      properties:
        overall:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Overall extraction confidence score
        field_scores:
          type: object
          additionalProperties:
            type: number
            format: float
            minimum: 0.0
            maximum: 1.0
          description: Confidence score for each extracted field

    ProcessingSummary:
      type: object
      required:
        - total_images
        - successful_extractions
        - failed_extractions
        - total_processing_time_ms
      properties:
        total_images:
          type: integer
          description: Total number of images submitted
        successful_extractions:
          type: integer
          description: Number of successfully processed images
        failed_extractions:
          type: integer
          description: Number of failed image extractions
        total_processing_time_ms:
          type: integer
          description: Total processing time for all images
        average_confidence:
          type: number
          format: float
          nullable: true
          description: Average confidence across all successful extractions

    ProcessingError:
      type: object
      required:
        - error_type
        - message
      properties:
        error_type:
          type: string
          enum:
            - configuration_error
            - validation_error
            - api_error
            - timeout_error
            - network_error
            - parse_error
          description: Category of error encountered
        message:
          type: string
          description: Human-readable error description
        image_index:
          type: integer
          nullable: true
          description: Index of image that caused error (if applicable)
        retry_after_seconds:
          type: integer
          nullable: true
          description: Suggested retry delay for rate limit errors

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details

    RateLimitError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          properties:
            retry_after_seconds:
              type: integer
              description: Seconds to wait before retrying
            quota_remaining:
              type: integer
              nullable: true
              description: Remaining API quota if available

    ServiceUnavailableError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          properties:
            service_status:
              type: string
              description: Status of the Gemini API service
            estimated_recovery_time:
              type: string
              format: date-time
              nullable: true
              description: Estimated service recovery time